id: IB7F8B577
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T08:54:13+00:00'
last_modified: '2022-06-08T01:08:26.450547+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3PD109
  title: 中国历史地图集
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    C4C4:
      image_group_id: I2PD15094
      title: ''
      total_pages: 129
      order: 1
      base_file: C4C4.txt
    429E:
      image_group_id: I2PD15095
      title: ''
      total_pages: 149
      order: 2
      base_file: 429E.txt
    E68D:
      image_group_id: I2PD15096
      title: ''
      total_pages: 139
      order: 3
      base_file: E68D.txt
    DCDC:
      image_group_id: I2PD15097
      title: ''
      total_pages: 157
      order: 4
      base_file: DCDC.txt
    7F20:
      image_group_id: I2PD15098
      title: ''
      total_pages: 220
      order: 5
      base_file: 7F20.txt
    '6220':
      image_group_id: I2PD15099
      title: ''
      total_pages: 191
      order: 6
      base_file: 6220.txt
    3D19:
      image_group_id: I2PD15100
      title: ''
      total_pages: 231
      order: 7
      base_file: 3D19.txt
    '1636':
      image_group_id: I2PD15101
      title: ''
      total_pages: 197
      order: 8
      base_file: 1636.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
